# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hamza 
brief-intro: Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ismnoiet.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: ham_ism 
github_username: ismnoiet 
email: ismnoiet@gmail.com

description_footer: Be Thankful Over Few God Makes You Happy Over Many 

# comments
# replace my disqus username with yours.
disqus_shortname: ismnoiet-github-blog 

# google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
