# Site settings
title: Hamza
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ismnoiet.github.io" # the base hostname & protocol for your site

author:
  fullname: Hamza 
  googleplus: https://plus.google.com/u/0/+hamisml 
  github: ismnoiet
  twitter: ham_ism
  gplus: hamisml
  disqus: ismnoiet-github-blog 
  # disqus: your_disqus_username
# google_analytics: 'UA-XXXXXXXX-X'

gems:
  - jekyll-gist 
# Build settings
markdown: kramdown